@host = http://localhost:5069

###
GET {{host}}/api/products
Accept: application/json

###
GET {{host}}/api/products/1
Accept: application/json

###
GET {{host}}/api/customers
Accept: application/json

###
POST {{host}}/api/purchase-orders
Content-Type: application/json

{
  "customerId": 1,
  "productIds": [3, 1, 5]
}

###
GET {{host}}/api/purchase-orders/1
Accept: application/json

###
GET {{host}}/api/purchase-orders/1/shipping-slip
Accept: application/json

###
GET {{host}}/api/customers/1
Accept: application/json

###
POST {{host}}/api/purchase-orders
Content-Type: application/json

{
  "customerId": 0,
  "productIds": []
}
